# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'B3Utils' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for B3Utils
  pod 'Google/SignIn'

  target 'B3UtilsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'B3Utils-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for B3Utils-tvOS

  target 'B3Utils-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
